version: "2"

services:
  zk:
    image: mesoscloud/zookeeper:3.4.8-centos
    network_mode: host
    environment:
      MYID: 1

  master:
    image: mesosphere/mesos-master:0.28.1-2.0.20.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave:0.28.1-2.0.20.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

#    slave-two:
#      image: mesosphere/mesos-slave:0.28.1-2.0.20.ubuntu1404
#      network_mode: host
#      pid: host
#      environment:
#        MESOS_MASTER: zk://127.0.0.1:2181/mesos
#        MESOS_CONTAINERIZERS: docker,mesos
#        MESOS_PORT: 5052
#        MESOS_RESOURCES: ports(*):[12000-12999]
#        MESOS_HOSTNAME: ${DOCKER_IP}
#        LIBPROCESS_IP: ${DOCKER_IP}
#      volumes:
#        - /sys/fs/cgroup:/sys/fs/cgroup
#        - /usr/local/bin/docker:/usr/bin/docker
#        - /var/run/docker.sock:/var/run/docker.sock
#        - ${PWD}/resolv.conf:/etc/resolv.conf
#      depends_on:
#        - zk

  marathon:
    image: mesosphere/marathon:v1.1.1
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    depends_on:
      - zk

#  mesos-dns:
#    image: mesosphere/mesos-dns:0.5.2
#    network_mode: host
#    volumes:
#      - ${PWD}/config.json:/config.json
#      - ${PWD}/logs:/tmp
#    entrypoint:
#      - /usr/bin/mesos-dns
#      - -v=2
#      - -config=/config.json
#    depends_on:
#      - master